service: pi-web-pubsub-py-be
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
    GCP_PUBSUB_TOPIC_COMMANDS: gpio_commands_topic
    GCP_PUBSUB_SUBSCRIPTION_COMMANDS: gpio_commands_subscription
    GCP_PUBSUB_TOPIC_STATUS: gpio_status_topic
