service: pi-web-pubsub-node-full
runtime: nodejs
env: flex

env_variables:
    GCP_PUBSUB_TOPIC_COMMANDS: gpio_commands_topic
    GCP_PUBSUB_SUBSCRIPTION_COMMANDS: gpio_commands_subscription
    GCP_PUBSUB_TOPIC_STATUS: gpio_status_topic
